services:
  nexus:
    image: ms-nosql_nexus:1.0
    container_name: ms-nosql_nexus
    build:
      context: .
      dockerfile: Dockerfile.nexus
    ports:
      - "8081:8081"
      - "5000:5000"
    restart: unless-stopped

volumes:
  nexus-data: